-- iStreams CRM - PostgreSQL schema (final state of the SQL Server scripts 01-08).
-- Run once on an empty database:  psql -d istreams_crm -f 01_schema.sql
-- Timestamps are stored as UTC in "timestamp" columns. Text columns are case-sensitive,
-- so the API compares emails / codes with LOWER() and searches with ILIKE.

CREATE OR REPLACE FUNCTION utc_now() RETURNS timestamp
    LANGUAGE sql STABLE AS $$ SELECT now() AT TIME ZONE 'utc' $$;

CREATE TABLE IF NOT EXISTS wsm_companies (
    company_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code   VARCHAR(20)  NOT NULL,
    company_name   VARCHAR(150) NOT NULL,
    status         VARCHAR(10)  NOT NULL DEFAULT 'PENDING',
    created_at     TIMESTAMP    NOT NULL DEFAULT utc_now(),
    approved_at    TIMESTAMP    NULL,
    CONSTRAINT ux_wsm_companies_code UNIQUE (company_code)
);

CREATE TABLE IF NOT EXISTS wsm_users (
    user_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      INT          NOT NULL REFERENCES wsm_companies(company_id),
    full_name       VARCHAR(150) NOT NULL,
    email           VARCHAR(150) NULL,
    mobile_no       VARCHAR(20)  NULL,
    password_hash   VARCHAR(255) NULL,
    role            VARCHAR(10)  NOT NULL DEFAULT 'STAFF',
    is_super_admin  CHAR(1)      NOT NULL DEFAULT 'F',
    is_active       CHAR(1)      NOT NULL DEFAULT 'T',
    last_login_at   TIMESTAMP    NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT utc_now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_wsm_users_email_notnull ON wsm_users (LOWER(email)) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_wsm_users_company_mobile ON wsm_users (company_id, mobile_no) WHERE mobile_no IS NOT NULL;

CREATE TABLE IF NOT EXISTS wsm_password_resets (
    reset_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INT         NOT NULL REFERENCES wsm_users(user_id),
    token_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMP   NOT NULL,
    used_at     TIMESTAMP   NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT utc_now(),
    CONSTRAINT ux_wsm_password_resets_hash UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS wsm_whatsapp_settings (
    company_id       INT           NOT NULL PRIMARY KEY REFERENCES wsm_companies(company_id),
    waba_id          VARCHAR(50)   NULL,
    phone_number_id  VARCHAR(50)   NULL,
    display_number   VARCHAR(30)   NULL,
    access_token     VARCHAR(1000) NULL,
    verify_token     VARCHAR(200)  NULL,
    app_secret       VARCHAR(200)  NULL,
    is_verified      CHAR(1)       NOT NULL DEFAULT 'F',
    verified_name    VARCHAR(200)  NULL,
    updated_at       TIMESTAMP     NOT NULL DEFAULT utc_now()
);

CREATE TABLE IF NOT EXISTS wsm_customers (
    customer_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INT          NOT NULL REFERENCES wsm_companies(company_id),
    mobile_no           VARCHAR(20)  NULL,
    customer_name       VARCHAR(150) NULL,
    email               VARCHAR(150) NULL,
    whatsapp_name       VARCHAR(150) NULL,
    chat_state          VARCHAR(20)  NOT NULL DEFAULT 'DONE',
    source              VARCHAR(20)  NOT NULL DEFAULT 'WhatsApp',
    assigned_to         INT          NULL REFERENCES wsm_users(user_id),
    assigned_at         TIMESTAMP    NULL,
    unread_count        INT          NOT NULL DEFAULT 0,
    email_unread_count  INT          NOT NULL DEFAULT 0,
    last_inbound_at     TIMESTAMP    NULL,
    last_message_at     TIMESTAMP    NULL,
    last_email_at       TIMESTAMP    NULL,
    bot_lead_id         INT          NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT utc_now(),
    updated_at          TIMESTAMP    NOT NULL DEFAULT utc_now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_wsm_customers_mobile_notnull ON wsm_customers (company_id, mobile_no) WHERE mobile_no IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_wsm_customers_email ON wsm_customers (company_id, LOWER(email));
CREATE INDEX IF NOT EXISTS ix_wsm_customers_assigned ON wsm_customers (company_id, assigned_to);

CREATE TABLE IF NOT EXISTS wsm_messages (
    message_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     INT          NOT NULL REFERENCES wsm_companies(company_id),
    customer_id    INT          NOT NULL REFERENCES wsm_customers(customer_id) ON DELETE CASCADE,
    wa_message_id  VARCHAR(200) NULL,
    direction      VARCHAR(3)   NOT NULL,
    msg_type       VARCHAR(20)  NOT NULL DEFAULT 'text',
    body           TEXT         NULL,
    status         VARCHAR(20)  NOT NULL,
    error_text     VARCHAR(500) NULL,
    is_bot         CHAR(1)      NOT NULL DEFAULT 'F',
    sent_by        INT          NULL REFERENCES wsm_users(user_id),
    created_at     TIMESTAMP    NOT NULL DEFAULT utc_now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_wsm_messages_wa_id ON wsm_messages (wa_message_id) WHERE wa_message_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_wsm_messages_customer ON wsm_messages (customer_id, created_at);

CREATE TABLE IF NOT EXISTS wsm_assignment_history (
    history_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    INT       NOT NULL REFERENCES wsm_companies(company_id),
    customer_id   INT       NOT NULL REFERENCES wsm_customers(customer_id) ON DELETE CASCADE,
    from_user_id  INT       NULL REFERENCES wsm_users(user_id),
    to_user_id    INT       NULL REFERENCES wsm_users(user_id),
    assigned_by   INT       NULL REFERENCES wsm_users(user_id),
    created_at    TIMESTAMP NOT NULL DEFAULT utc_now()
);

CREATE TABLE IF NOT EXISTS wsm_notes (
    note_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  INT          NOT NULL REFERENCES wsm_companies(company_id),
    title       VARCHAR(200) NOT NULL,
    content     TEXT         NULL,
    created_by  INT          NULL REFERENCES wsm_users(user_id),
    updated_by  INT          NULL REFERENCES wsm_users(user_id),
    created_at  TIMESTAMP    NOT NULL DEFAULT utc_now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT utc_now()
);

CREATE TABLE IF NOT EXISTS wsm_email_settings (
    company_id       INT          NOT NULL PRIMARY KEY REFERENCES wsm_companies(company_id),
    email_address    VARCHAR(150) NOT NULL,
    from_name        VARCHAR(150) NULL,
    username         VARCHAR(150) NOT NULL,
    password         VARCHAR(500) NULL,
    imap_host        VARCHAR(150) NOT NULL,
    imap_port        INT          NOT NULL DEFAULT 993,
    smtp_host        VARCHAR(150) NOT NULL,
    smtp_port        INT          NOT NULL DEFAULT 587,
    is_verified      CHAR(1)      NOT NULL DEFAULT 'F',
    uid_validity     BIGINT       NULL,
    last_uid         BIGINT       NULL,
    last_checked_at  TIMESTAMP    NULL,
    last_error       VARCHAR(500) NULL,
    updated_at       TIMESTAMP    NOT NULL DEFAULT utc_now()
);

CREATE TABLE IF NOT EXISTS wsm_emails (
    email_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    INT          NOT NULL REFERENCES wsm_companies(company_id),
    customer_id   INT          NOT NULL REFERENCES wsm_customers(customer_id) ON DELETE CASCADE,
    direction     VARCHAR(3)   NOT NULL,
    message_id    VARCHAR(500) NULL,
    subject       VARCHAR(500) NULL,
    from_address  VARCHAR(150) NULL,
    to_address    VARCHAR(150) NULL,
    body          TEXT         NULL,
    status        VARCHAR(20)  NOT NULL,
    error_text    VARCHAR(500) NULL,
    sent_by       INT          NULL REFERENCES wsm_users(user_id),
    created_at    TIMESTAMP    NOT NULL DEFAULT utc_now()
);
CREATE INDEX IF NOT EXISTS ix_wsm_emails_customer ON wsm_emails (customer_id, created_at);
CREATE INDEX IF NOT EXISTS ix_wsm_emails_message_id ON wsm_emails (company_id, message_id) WHERE message_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS wsm_projects (
    project_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id        INT           NOT NULL REFERENCES wsm_companies(company_id),
    project_seq       INT           NOT NULL,
    project_name      VARCHAR(200)  NOT NULL,
    description       TEXT          NULL,
    project_type      VARCHAR(20)   NOT NULL DEFAULT 'COMMUNITY',
    developer         VARCHAR(150)  NULL,
    emirate           VARCHAR(30)   NOT NULL,
    community         VARCHAR(150)  NULL,
    map_url           VARCHAR(500)  NULL,
    completion        VARCHAR(10)   NOT NULL DEFAULT 'OFFPLAN',
    handover_date     DATE          NULL,
    completion_pct    INT           NULL,
    amenities         VARCHAR(1000) NULL,
    down_payment_pct  NUMERIC(5,2)  NULL,
    payment_plan      VARCHAR(100)  NULL,
    is_active         CHAR(1)       NOT NULL DEFAULT 'T',
    created_by        INT           NULL REFERENCES wsm_users(user_id),
    created_at        TIMESTAMP     NOT NULL DEFAULT utc_now(),
    updated_at        TIMESTAMP     NOT NULL DEFAULT utc_now(),
    CONSTRAINT ux_wsm_projects_seq UNIQUE (company_id, project_seq)
);

CREATE TABLE IF NOT EXISTS wsm_project_payments (
    payment_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   INT          NOT NULL REFERENCES wsm_projects(project_id) ON DELETE CASCADE,
    step_no      INT          NOT NULL,
    label        VARCHAR(100) NOT NULL,
    percent_due  NUMERIC(5,2) NOT NULL,
    due_note     VARCHAR(100) NULL
);
CREATE INDEX IF NOT EXISTS ix_wsm_project_payments_project ON wsm_project_payments (project_id, step_no);

CREATE TABLE IF NOT EXISTS wsm_properties (
    property_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       INT           NOT NULL REFERENCES wsm_companies(company_id),
    ref_seq          INT           NOT NULL,
    title            VARCHAR(200)  NOT NULL,
    purpose          VARCHAR(10)   NOT NULL,
    property_type    VARCHAR(20)   NOT NULL,
    completion       VARCHAR(10)   NOT NULL DEFAULT 'READY',
    status           VARCHAR(12)   NOT NULL DEFAULT 'AVAILABLE',
    emirate          VARCHAR(30)   NOT NULL,
    community        VARCHAR(150)  NULL,
    sub_community    VARCHAR(150)  NULL,
    developer        VARCHAR(150)  NULL,
    map_url          VARCHAR(500)  NULL,
    bedrooms         INT           NULL,
    bathrooms        INT           NULL,
    bua_sqft         NUMERIC(12,2) NULL,
    plot_sqft        NUMERIC(12,2) NULL,
    parking          INT           NULL,
    view_type        VARCHAR(100)  NULL,
    floor_no         VARCHAR(20)   NULL,
    price            NUMERIC(18,2) NOT NULL,
    rent_frequency   VARCHAR(10)   NULL,
    cheques          INT           NULL,
    service_charge   NUMERIC(10,2) NULL,
    commission_pct   NUMERIC(5,2)  NULL,
    handover_date    DATE          NULL,
    payment_plan     VARCHAR(100)  NULL,
    completion_pct   INT           NULL,
    permit_no        VARCHAR(50)   NULL,
    title_deed_no    VARCHAR(50)   NULL,
    owner_name       VARCHAR(150)  NULL,
    owner_mobile     VARCHAR(20)   NULL,
    owner_email      VARCHAR(150)  NULL,
    furnishing       VARCHAR(12)   NULL,
    amenities        VARCHAR(1000) NULL,
    description      TEXT          NULL,
    is_featured      CHAR(1)       NOT NULL DEFAULT 'F',
    agent_id         INT           NULL REFERENCES wsm_users(user_id),
    created_by       INT           NULL REFERENCES wsm_users(user_id),
    updated_by       INT           NULL REFERENCES wsm_users(user_id),
    public_code      VARCHAR(12)   NULL,
    project_id       INT           NULL REFERENCES wsm_projects(project_id),
    created_at       TIMESTAMP     NOT NULL DEFAULT utc_now(),
    updated_at       TIMESTAMP     NOT NULL DEFAULT utc_now(),
    CONSTRAINT ux_wsm_properties_ref UNIQUE (company_id, ref_seq)
);
CREATE INDEX IF NOT EXISTS ix_wsm_properties_search ON wsm_properties (company_id, status, purpose, property_type, emirate);
CREATE UNIQUE INDEX IF NOT EXISTS ux_wsm_properties_public_code ON wsm_properties (public_code) WHERE public_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_wsm_properties_project ON wsm_properties (project_id);

CREATE TABLE IF NOT EXISTS wsm_property_files (
    file_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    INT          NOT NULL REFERENCES wsm_companies(company_id),
    property_id   INT          NOT NULL REFERENCES wsm_properties(property_id) ON DELETE CASCADE,
    file_kind     VARCHAR(10)  NOT NULL,
    file_name     VARCHAR(260) NOT NULL,
    stored_name   VARCHAR(100) NOT NULL,
    content_type  VARCHAR(100) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    is_cover      CHAR(1)      NOT NULL DEFAULT 'F',
    created_at    TIMESTAMP    NOT NULL DEFAULT utc_now()
);
CREATE INDEX IF NOT EXISTS ix_wsm_property_files_property ON wsm_property_files (property_id, file_kind);

CREATE TABLE IF NOT EXISTS wsm_services (
    service_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    INT           NOT NULL REFERENCES wsm_companies(company_id),
    service_name  VARCHAR(150)  NOT NULL,
    category      VARCHAR(50)   NOT NULL,
    price         NUMERIC(18,2) NULL,
    price_note    VARCHAR(50)   NULL,
    description   VARCHAR(2000) NULL,
    is_active     CHAR(1)       NOT NULL DEFAULT 'T',
    created_at    TIMESTAMP     NOT NULL DEFAULT utc_now(),
    updated_at    TIMESTAMP     NOT NULL DEFAULT utc_now()
);

CREATE TABLE IF NOT EXISTS wsm_leads (
    lead_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INT           NOT NULL REFERENCES wsm_companies(company_id),
    lead_seq           INT           NOT NULL,
    customer_id        INT           NOT NULL REFERENCES wsm_customers(customer_id) ON DELETE CASCADE,
    source             VARCHAR(20)   NOT NULL,
    purpose            VARCHAR(10)   NOT NULL,
    property_type      VARCHAR(20)   NULL,
    emirate            VARCHAR(30)   NULL,
    communities        VARCHAR(500)  NULL,
    bedrooms_min       INT           NULL,
    bedrooms_max       INT           NULL,
    budget_min         NUMERIC(18,2) NULL,
    budget_max         NUMERIC(18,2) NULL,
    finance            VARCHAR(15)   NULL,
    down_payment_max   NUMERIC(18,2) NULL,
    monthly_emi_max    NUMERIC(18,2) NULL,
    buy_plan           VARCHAR(15)   NULL,
    min_amenities      VARCHAR(1000) NULL,
    completion         VARCHAR(10)   NULL,
    move_timeline      VARCHAR(20)   NULL,
    nationality        VARCHAR(50)   NULL,
    buyer_type         VARCHAR(10)   NULL,
    requirements       VARCHAR(2000) NULL,
    status             VARCHAR(20)   NOT NULL DEFAULT 'NEW',
    priority           VARCHAR(5)    NOT NULL DEFAULT 'WARM',
    lost_reason        VARCHAR(20)   NULL,
    won_property_id    INT           NULL REFERENCES wsm_properties(property_id),
    deal_value         NUMERIC(18,2) NULL,
    commission_amount  NUMERIC(18,2) NULL,
    closed_at          TIMESTAMP     NULL,
    assigned_to        INT           NULL REFERENCES wsm_users(user_id),
    assigned_at        TIMESTAMP     NULL,
    created_by         INT           NULL REFERENCES wsm_users(user_id),
    created_at         TIMESTAMP     NOT NULL DEFAULT utc_now(),
    updated_at         TIMESTAMP     NOT NULL DEFAULT utc_now(),
    CONSTRAINT ux_wsm_leads_seq UNIQUE (company_id, lead_seq)
);
CREATE INDEX IF NOT EXISTS ix_wsm_leads_company ON wsm_leads (company_id, status, assigned_to);
CREATE INDEX IF NOT EXISTS ix_wsm_leads_customer ON wsm_leads (customer_id);

CREATE TABLE IF NOT EXISTS wsm_lead_activities (
    activity_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     INT           NOT NULL REFERENCES wsm_companies(company_id),
    lead_id        INT           NOT NULL REFERENCES wsm_leads(lead_id) ON DELETE CASCADE,
    activity_type  VARCHAR(10)   NOT NULL,
    body           VARCHAR(2000) NULL,
    outcome        VARCHAR(20)   NULL,
    property_id    INT           NULL REFERENCES wsm_properties(property_id),
    status_from    VARCHAR(20)   NULL,
    status_to      VARCHAR(20)   NULL,
    created_by     INT           NULL REFERENCES wsm_users(user_id),
    created_at     TIMESTAMP     NOT NULL DEFAULT utc_now()
);
CREATE INDEX IF NOT EXISTS ix_wsm_lead_activities_lead ON wsm_lead_activities (lead_id, created_at);

CREATE TABLE IF NOT EXISTS wsm_follow_ups (
    follow_up_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      INT           NOT NULL REFERENCES wsm_companies(company_id),
    lead_id         INT           NOT NULL REFERENCES wsm_leads(lead_id) ON DELETE CASCADE,
    follow_up_type  VARCHAR(10)   NOT NULL,
    due_at          TIMESTAMP     NOT NULL,
    notes           VARCHAR(1000) NULL,
    property_id     INT           NULL REFERENCES wsm_properties(property_id),
    assigned_to     INT           NULL REFERENCES wsm_users(user_id),
    is_done         CHAR(1)       NOT NULL DEFAULT 'F',
    done_at         TIMESTAMP     NULL,
    done_by         INT           NULL REFERENCES wsm_users(user_id),
    created_by      INT           NULL REFERENCES wsm_users(user_id),
    created_at      TIMESTAMP     NOT NULL DEFAULT utc_now()
);
CREATE INDEX IF NOT EXISTS ix_wsm_follow_ups_due ON wsm_follow_ups (company_id, is_done, due_at);
CREATE INDEX IF NOT EXISTS ix_wsm_follow_ups_lead ON wsm_follow_ups (lead_id);

CREATE TABLE IF NOT EXISTS wsm_lead_shares (
    share_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id   INT         NOT NULL REFERENCES wsm_companies(company_id),
    lead_id      INT         NOT NULL REFERENCES wsm_leads(lead_id) ON DELETE CASCADE,
    property_id  INT         NOT NULL REFERENCES wsm_properties(property_id),
    channel      VARCHAR(10) NOT NULL,
    shared_by    INT         NULL REFERENCES wsm_users(user_id),
    shared_at    TIMESTAMP   NOT NULL DEFAULT utc_now()
);
CREATE INDEX IF NOT EXISTS ix_wsm_lead_shares_lead ON wsm_lead_shares (lead_id, property_id);
