/* =============================================================================
   One-time import: copies the WhatsApp setup from the PM system
   (whatsapp_settings / whatsapp_customers / whatsapp_messages) into company #1.
   The super admin login reuses the PM password hash of baluinbox@gmail.com.
   Does nothing if any wsm_ company already exists. PM tables are only read.
   ============================================================================= */
USE project_management;
GO

IF EXISTS (SELECT 1 FROM dbo.wsm_companies)
BEGIN
    PRINT 'wsm_companies already has data - import skipped.';
    RETURN;
END

SET XACT_ABORT ON;
BEGIN TRAN;

DECLARE @name NVARCHAR(150) = N'iStreams';
IF OBJECT_ID('dbo.whatsapp_settings', 'U') IS NOT NULL
    SELECT @name = COALESCE(NULLIF(LTRIM(RTRIM(LEFT(verified_name, CHARINDEX(N' · ', verified_name + N' · ') - 1))), ''), @name)
    FROM dbo.whatsapp_settings WHERE settings_id = 1;

INSERT INTO dbo.wsm_companies (company_code, company_name, status, approved_at)
VALUES (LOWER(REPLACE(LEFT(CONVERT(VARCHAR(36), NEWID()), 13), '-', '')), @name, 'ACTIVE', SYSUTCDATETIME());
DECLARE @company INT = SCOPE_IDENTITY();

INSERT INTO dbo.wsm_users (company_id, full_name, email, password_hash, role, is_super_admin)
SELECT @company, ISNULL(e.full_name, N'Super Admin'), N'baluinbox@gmail.com', e.password_hash, 'ADMIN', 'T'
FROM (SELECT 1 AS x) d
LEFT JOIN dbo.employees e ON e.email = N'baluinbox@gmail.com';

IF OBJECT_ID('dbo.whatsapp_settings', 'U') IS NOT NULL
    INSERT INTO dbo.wsm_whatsapp_settings
        (company_id, waba_id, phone_number_id, display_number, access_token, verify_token, app_secret, is_verified, verified_name)
    SELECT @company, waba_id, phone_number_id, display_number, access_token, verify_token, app_secret, is_verified, verified_name
    FROM dbo.whatsapp_settings WHERE settings_id = 1;

IF OBJECT_ID('dbo.whatsapp_customers', 'U') IS NOT NULL
BEGIN
    INSERT INTO dbo.wsm_customers
        (company_id, mobile_no, customer_name, email, whatsapp_name, chat_state, source,
         unread_count, last_inbound_at, last_message_at, created_at, updated_at)
    SELECT @company, mobile_no, customer_name, email, whatsapp_name, chat_state, source,
           ISNULL(unread_count, 0), last_inbound_at, last_message_at, created_at, updated_at
    FROM dbo.whatsapp_customers;

    IF OBJECT_ID('dbo.whatsapp_messages', 'U') IS NOT NULL
        INSERT INTO dbo.wsm_messages
            (company_id, customer_id, wa_message_id, direction, msg_type, body, status, error_text, is_bot, created_at)
        SELECT @company, nc.customer_id, m.wa_message_id, RTRIM(m.direction), m.msg_type, m.body, m.status,
               m.error_text, m.is_bot, m.created_at
        FROM dbo.whatsapp_messages m
        JOIN dbo.whatsapp_customers oc ON oc.customer_id = m.customer_id
        JOIN dbo.wsm_customers nc ON nc.company_id = @company AND nc.mobile_no = oc.mobile_no
        ORDER BY m.message_id;
END

INSERT INTO dbo.wsm_notes (company_id, title, content) VALUES (@company, N'How this WhatsApp CRM works', N'# Daily flow
1. A customer sends a WhatsApp message to the company number.
2. The bot asks for name and email and saves the customer as Unassigned.
3. Admin opens WhatsApp Inbox -> Unassigned and assigns the customer to a staff member.
4. The staff member sees the chat under My Chats and replies from the browser.
5. Admin can reassign at any time; the new staff member sees the full history.

# Roles
- Admin: whole inbox, assign / reassign, Staff, Customers, WhatsApp Settings.
- Staff: only customers assigned to them.
- Super Admin: approves or suspends companies that sign up.

# WhatsApp rules
- Free-form replies are allowed within 24 hours of the customer''s last message.
- After 24 hours the reply box closes until the customer writes again.

# WhatsApp Settings (Admin)
- Phone Number ID, WABA ID, Access Token: Meta App -> WhatsApp -> API Setup.
- App Secret: Meta App -> App Settings -> Basic (32 characters, generated by Meta).
- Verify Token: any secret word; enter the same word in Meta.
- Callback URL: shown on the WhatsApp Settings page (unique per company).
- In Meta subscribe the webhook field "messages", and make sure the WhatsApp
  Business Account is subscribed to the app (POST /{WABA-ID}/subscribed_apps).');

COMMIT;

SELECT c.company_id, c.company_code, c.company_name,
       (SELECT COUNT(*) FROM dbo.wsm_users     WHERE company_id = c.company_id) AS users,
       (SELECT COUNT(*) FROM dbo.wsm_customers WHERE company_id = c.company_id) AS customers,
       (SELECT COUNT(*) FROM dbo.wsm_messages  WHERE company_id = c.company_id) AS messages
FROM dbo.wsm_companies c;
GO
